name: commerciosdk
description: Pure Dart library allowing you to easily integrate with the Commercio.network blockchain
version: 2.1.2
homepage: https://github.com/commercionetwork/sdk.dart
documentation: https://dart.sdk.docs.commercio.network

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  hex: ^0.1.2
  http: ^0.12.0
  equatable: ^1.0.1
  json_annotation: ^3.0.0
  uuid: ^2.0.2
  asn1lib: ^0.6.4
  basic_utils: ^2.5.3

  # Crypto utils
  sacco: ^0.1.4
  encrypt: ^4.0.1
  ed25519_hd_key: ^1.0.1
  pointycastle: ^1.0.1
  steel_crypt: ^1.7.1


dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.9+1
  collection: ^1.14.13
  json_serializable: ^3.2.0
  mockito: ^4.1.1
  test: ^1.9.3
  test_coverage: ^0.4.1
